### ISSUE TITLE
Not working in Yii2 Advance template

### ISSUE THREAD

**Issue by baltechies** [noam148/yii2-image-manager#35] opened 2017-09-10 08:37 UTC
Hi,

I am facing issue in Yii2 advance template. Image uploading is working fine but its showing wrong path in TextEditor(dosamigos\tinymce\TinyMce) after select an image. It adding ../ in image path. But image is not loading in frontend application. I have different subdomains for backend and frontend application. Can you please suggest how I can use it?

**Comment by noam148** [comment] 2017-09-20 10:59
Sorry for my late response, I was very busy these days.

Here maybe a solution. Set in your config the propertie  "absoluteUrl" to true in the imagemanager component. It generate a image path with the full domain. I think it generate a image with the backend url, but the image will be generate and loading. Let me know if the solution works!

`'components' => [
    'imagemanager' => [
		'absoluteUrl' => true,
	],
],`

**Comment by baltechies** [comment] 2017-09-20 11:11
@noam148  I already tried this solution but its not working in TinyMce editor. At the time of image browse it return image path with absoluteUrl, but after select the image its get replaced with ../ in image src. When I m viewing the source code in TinyMce editor, then image src is like `<img src="../assets/image/test.jpg">`

**Comment by noam148** [comment] 2017-09-20 11:17
I need to take a look to it. Can you give me an example of your folder structure and a example of you domains so i can reconstruct you scenario? 

**update: And what your config is of your module and component for both envoirments?**

**Comment by baltechies** [comment] 2017-09-20 11:40
folder structure is same as in Yii2 advance project.
my frontend domain is like **mydomain.local** and backend domain is **mydomain.backend**

**Module config is**
 `'modules' => [	'imagemanager' => [
		'class' => 'noam148\imagemanager\Module',
		//set accces rules ()
		'canUploadImage' => true,
		'canRemoveImage' => function(){
			return true;
		},
		'deleteOriginalAfterEdit' => false, // false: keep original image after edit. true: delete original image after edit
		// Set if blameable behavior is used, if it is, callable function can also be used
		'setBlameableBehavior' => false,
		//add css files (to use in media manage selector iframe)
		'cssFiles' => [
			'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css',
		],
	],`

**Component config is :**
 `'components' => ['imagemanager' => [
            'class' => 'noam148\imagemanager\components\ImageManagerGetPath',
            //set media path (outside the web folder is possible)
            'mediaPath' => dirname(dirname(__DIR__)) .'/frontend/web/media/upload',
            //path relative web folder to store the cache images
            'cachePath' => 'assets/images',
            //use filename (seo friendly) for resized images else use a hash
            'useFilename' => true,
            //show full url (for example in case of a API)
            'absoluteUrl' => ture,
            'databaseComponent' => 'db' // The used database component by the image manager, this defaults to the Yii::$app->db component
	],]`


Images are saved correctly I am able to upload, crop images. Only issue with Yii2 advance project to show images in content in of frontend domain. I think it will work fine in Yii2 basic project. 

Let me know if you need more information to debug this issue.

**Comment by noam148** [comment] 2017-09-20 11:59
Thanks, is this config set in your common config or has the front and back-end his own config?

I was not so clear about the folder structure. What i mean is de location of your webroot of you frontend, backend, and the folder where to store the images?

**Comment by baltechies** [comment] 2017-09-20 12:46
yes this is the config of common config files.

Folder structure for frontend application is 
![screen shot 2017-09-20 at 6 12 43 pm](https://user-images.githubusercontent.com/13519944/30644277-7f4f93fa-9e2f-11e7-85c2-268617888222.png)


Folder structure for backend application is 
![screen shot 2017-09-20 at 6 16 55 pm](https://user-images.githubusercontent.com/13519944/30644438-0098c5d0-9e30-11e7-920d-551358fe3802.png)



Main file is stored in fortend/web/media/upload but cache file is stores in backend/web/assests/

I am uploading files from backend.

**Comment by noam148** [comment] 2017-09-20 13:17
I see in your component config a typo: `'absoluteUrl' => ture,` (in stead of true). Can you try to replace it?

**Comment by baltechies** [comment] 2017-09-20 13:41
Yes I tried it,  but not working. Main problem is that temp(asset) image path is returned, on select an image in TinyMce editor. But asset folder is pointing to backend only. Because we are uploading images from backend application. But when are loading content in frontend then images not found. because frontend  asset folder do not have any image.

**Comment by noam148** [comment] 2017-09-20 13:49
Okay, I need take a look how to fix it. Unfortuntly i'm very busy to plan a trip. Over 3 weeks i'm for 5 weeks on holiday so i dont have a lot time to see what the issue is. I will do my best to fix it before that time but i can't promis it :(

**Comment by noam148** [comment] 2018-02-18 19:44
@baltechies, @isalcedo create a fix and the code is merged. Let me know is the problem is solved!

Update the image manager to te last version for the fix.

Thanks al lot @isalcedo!

**Closed as completed by noam148** 2018-02-18 19:44 UTC
